name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for release-drafter)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Draft release notes
        id: draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from draft title
        run: |
          version=$(echo "${{ steps.draft.outputs.name }}" | grep -oP 'v\\d+\\.\\d+\\.\\d+')
          echo "VERSION=${version#v}" >> $GITHUB_ENV

      - name: Tag the commit with release version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f ${{ steps.version.outputs.version }}
          git push origin -f ${{ steps.version.outputs.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body: ${{ steps.draft.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}